config/routes.rb
DailyStandup::Application.routes.draw do
  root "home#index"

  resources :groups, only: [:index, :show] do
    resources :days, only: [:index, :show] do
      resources :posts, only: [:index, :show, :new, :create] do
        resources :comments, only: [:new, :create]
      end
    end
  end

  # Session login/logout
  get    "login"  => "sessions#new",     as: :login
  post   "login"  => "sessions#create"
  get    "logout" => "sessions#destroy", as: :logout
  delete "logout" => "sessions#destroy"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/standup.rb
class Standup
  def groups
    Group.all
  end

  def users_for group
    group.users
  end

  def is_member_of? group, user
    group.is_member? user
  end

  def add_user_to group, user
    group.add_member user
  end

  def remove_user_from group, user
    group.remove_member user
  end

  def posts_for group, date
    group.posts_for date
  end

  def post_for group, user, date
    group.post_for user, date
  end

  def add_post group, user, date, body
    group.add_post user, date, body
  end

  def comments_for post
    post.comments
  end

  def add_comment post, user, body
    post.comments.create user: user, body: body
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true

  def self.authenticate email, password
    user = find_by_email email
    if user && user.authenticate(password)
      user
    else
      Invalid.new email
     end
   end
end

app/models/user/invalid.rb
class User
  class Invalid
    include ActiveModel::Model

    attr_accessor :email, :password
    attr_reader   :errors

    def initialize email
      @email = email
      @errors = ActiveModel::Errors.new(self)
      errors.add :email,    "must be entered" if @email.blank?
      errors.add :password, "is not correct"
    end

    def self.model_name
      ActiveModel::Name.new User
    end

    def valid?;      false; end
    def new_record?; true;  end
    def persisted?;  false; end
    def destroyed?;  false; end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def logged_in?
    current_user.present?
   end
   helper_method :logged_in?

   def current_user
     @current_user ||= User.find_by_id session[:user_id]
   end
   helper_method :current_user

   def login! user
     session[:user_id] = user.try(:id)
   end

   def logout!
     session[:user_id] = nil
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_group_and_day_and_post_and_comments

  # GET /comments/new
  def new
    @comment = @comments.new
  end

  # POST /comments
  def create
    @comment = Standup.new.add_comment @post, current_user, comment_params[:body]

    if @comment.valid?
      redirect_to group_day_post_url(@group, @day, @post), notice: "Comment was successfully created."
    else
      render action: "new"
    end
  end

  private

  def set_group_and_day_and_post_and_comments
    standup = Standup.new
    @group = standup.groups.find params[:group_id]
    @day = date
    @post = @group.posts_for(@day).find params[:post_id]
    @comments = @post.comments
  end

  def date
    case params[:id]
    when "today"
      Date.today
    when "yesterday"
      Date.yesterday
    when "tomorrow"
      Date.tomorrow
    else
      Date.parse params[:day_id]
    end
  rescue ArgumentError
    raise ActiveRecord::RecordNotFound
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params[:comment]
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :set_group
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to group_path(@group)
  end

  def index
    @day = Date.today
    @prev = @day.prev_day
    @next = @day.next_day
    @posts = @group.posts_for @day
    render "posts/index"
  end

  def show
    @day = date
    @prev = @day.prev_day
    @next = @day.next_day
    @posts = @group.posts_for @day
    render "posts/index"
  end

  protected

  def set_group
    @group = Standup.new.groups.find params[:group_id]
  end

  def date
    case params[:id]
    when "today"
      Date.today
    when "yesterday"
      Date.yesterday
    when "tomorrow"
      Date.tomorrow
    else
      Date.parse params[:id]
    end
  rescue ArgumentError
    raise ActiveRecord::RecordNotFound
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Standup.new.groups
  end

  def show
    @group = Standup.new.groups.find params[:id]
    @day = Date.today
    @prev = @day.prev_day
    @next = @day.next_day
    @posts = @group.posts_for @day
    render "posts/index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PermissionsHelper
  before_action :set_group_and_day_and_posts
  before_action :set_post, only: [:show]
  # before_filter :enforce_login, only: [:new, :create]

  # GET /groups/:group_id/days/:day_id/posts
  def index
    @prev = @day.prev_day
    @next = @day.next_day
  end

  # GET /groups/:group_id/days/:day_id/posts/1
  def show
  end

  # GET /groups/:group_id/days/:day_id/posts/new
  def new
    return redirect_to group_day_posts_path(@group, @day) unless can_create_post?

    @post = @posts.new
  end

  # POST /groups/:group_id/days/:day_id/posts
  def create
    @post = Standup.new.add_post @group, current_user, @day, post_params[:body]

    if @post.valid?
      redirect_to group_day_post_url(@group, @day, @post), notice: "Post was successfully created."
    else
      render action: "new"
    end
  end

  private

  def already_has_post?
    Standup.new.post_for(@group, current_user, @day).present?
  end

  def set_group_and_day_and_posts
    standup = Standup.new
    @group = standup.groups.find params[:group_id]
    @day = date
    @posts = standup.posts_for @group, @day
  end

  def date
    case params[:id]
    when "today"
      Date.today
    when "yesterday"
      Date.yesterday
    when "tomorrow"
      Date.tomorrow
    else
      Date.parse params[:day_id]
    end
  rescue ArgumentError
    raise ActiveRecord::RecordNotFound
  end

  def set_post
    @post = @posts.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params[:post]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /login
  def new
    @user = User.new
  end

  # POST /login
  def create
    @user = User.authenticate session_params[:email], session_params[:password]

    if @user.valid?
      login! @user
      redirect_to root_url, notice: "Logged in!"
    else
      render action: "new"
    end
  end

  # DELETE /logout
  def destroy
    logout!
    redirect_to root_url, notice: "Logged out!"
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
  def can_create_post?
    return false if current_user.blank?
    if @group.present? && @day.present? &&
        Standup.new.is_member_of?(@group, current_user)
      post_on_day = Standup.new.post_for @group, current_user, @day
      return post_on_day.blank?
    end
    return false
  end

  def can_update_post?
    false
  end
  def can_create_comment?
    current_user.present?
  end

end

app/views/comments/_form.html.erb
<%= form_for @comment, url: group_day_post_comments_url(@group, @day, @post) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, class: "sr-only" %>
    <%= f.text_area :body, class: "forom-control", placeholder: "Post" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', group_day_post_url(@group, @day, @post) %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<% @groups.each do |group| %>
  <h3><%= link_to group.name, group %></h3>
  <p>Today <%= pluralize group.posts_for(Date.today).count, "post" %> -
     Yesterday <%= pluralize group.posts_for(Date.yesterday).count, "post" %></p>
<% end %>

app/views/home/index.html.erb
<h1>Daily Standup</h1>
<p>Welcome!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daily Standup</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="/javascripts/html5shiv.js"></script>
    <script src="/javascripts/respond.min.js"></script>
  <![endif]-->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Standup</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Hello #{current_user.name}!", "#" %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, url: group_day_posts_url(@group, @day) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, class: "sr-only" %>
    <%= f.text_area :body, class: "forom-control", placeholder: "Post" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1><%= @group.name %></h1>
<p>
  <%= link_to group_day_path@group, @prev do %>
    Previous <%= pluralize @group.posts_for(@prev).count, "post" %>
  <% end %>
  -
  <%= @day %> <%= pluralize @group.posts_for(@day).count, "post" %>
  -
  <%= link_to group_day_path@group, @next do %>
    Next <%= pluralize @group.posts_for(@next).count, "post" %>
  <% end %>
</p>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= post.user.name %>
      <%= link_to "says:", group_day_post_path(post.group, post.date, post) %>
      <%= post.body %> - <%= pluralize post.comments.count, "comment" %>
    </li>
  <% end %>
</ul>

<% if can_create_post? %>
  <%= link_to 'New Post', new_group_day_post_url(@group, @day) %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', group_day_posts_url(@group, @day) %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= @post.user.name %> says:
  </div>
  <div class="col-lg-8">
    <%= @post.body %>
  </div>
</div>
<h3>Comments</h3>
<% @post.comments.in_groups_of(3, false) do |comments| %>
  <div class="row">
    <% comments.each do |comment| %>
      <div class="col-lg-4">
        <%= comment.user.name %> says:
        <%= comment.body %>
      </div>
    <% end %>
  </div>
<% end %>

<%= link_to 'Add Comment', new_group_day_post_comment_url(@group, @day, @post) %> |
<%= link_to 'Back', group_day_posts_url(@group, @day) %>